/**
 * Aletheia Verification Certificate Generator
 *
 * Generates cryptographically-structured, downloadable provenance certificates.
 * Currently generated client-side pending production server-side certificate
 * authority infrastructure.
 *
 * In production: certificates are signed by the Aletheia server CA
 * and timestamped by a trusted timestamp authority (RFC 3161).
 */

import { sha256Hex, shorten, type VerifyResult, type SignatureBundle } from "@/lib/aletheia";
import type { ForensicReport } from "@/lib/forensics/engine";
import type { SemanticAnalysisResult } from "@/lib/semantic/analysis";

// ─── Certificate Types ────────────────────────────────────────────────────────

export type CertificateClass =
  | "PROVENANCE_CERTIFICATE"
  | "INTEGRITY_REPORT"
  | "FORENSIC_AUDIT"
  | "LINEAGE_MANIFEST";

export interface VerificationCertificate {
  /** Schema identifier */
  aletheia_certificate: "v2";
  /** Unique certificate ID */
  certificate_id: string;
  /** Certificate class */
  certificate_class: CertificateClass;
  /** ISO 8601 issuance timestamp */
  issued_at: string;
  /** Issuer metadata */
  issuer: CertificateIssuer;
  /** Subject (what is being certified) */
  subject: CertificateSubject;
  /** Core verification result */
  verification: CertificateVerification;
  /** Forensic audit section (optional) */
  forensic_audit?: CertificateForensicSection;
  /** Lineage reference (optional) */
  lineage?: { root_id: string | null; summary?: string };
  /** Legal and scope disclaimers */
  scope_notes: ScopeNotes;
  /** Certificate hash (self-referential integrity check) */
  certificate_hash?: string;
}

export interface CertificateIssuer {
  name: string;
  version: string;
  infrastructure_note: string;
}

export interface CertificateSubject {
  media_hash: string;
  device_id: string;
  capture_timestamp: string;
  algorithm: string;
  gps: { lat: number; lon: number } | null;
  bundle_version: number;
  ai_disclosure: string;
}

export interface CertificateVerification {
  overall_valid: boolean;
  trust_level: string;
  trust_score: number;
  hash_match: boolean;
  signature_valid: boolean;
  timestamp_valid: boolean;
  replay_protected: boolean;
  checks: Array<{ label: string; passed: boolean }>;
}

export interface CertificateForensicSection {
  synthetic_risk_score: number;
  verdict: string;
  confidence: number;
  primary_indicators: string[];
  check_count: number;
  checks_passed: number;
  provenance_audit_score: number;
}

export interface ScopeNotes {
  what_is_verified: string[];
  what_is_not_verified: string[];
  provenance_disclaimer: string;
  semantic_disclaimer: string;
  legal_disclaimer: string;
}

// ─── Scope content ────────────────────────────────────────────────────────────

const SCOPE: ScopeNotes = {
  what_is_verified: [
    "SHA-256 cryptographic hash integrity",
    "Ed25519 digital signature validity",
    "Device identity binding (public key derivation)",
    "Timestamp validity and non-future constraint",
    "Cryptographic nonce presence (replay protection)",
    "Bundle schema completeness",
  ],
  what_is_not_verified: [
    "Semantic truth or objectivity of depicted content",
    "Whether depicted events actually occurred",
    "Whether scenes were staged or manipulated pre-capture",
    "Whether media was AI-generated before signing",
    "Whether sensor inputs were spoofed at capture time",
    "Whether GPS coordinates reflect actual capture location",
  ],
  provenance_disclaimer:
    "This certificate verifies cryptographic provenance integrity. It does not validate the semantic truth or objective reality of depicted content.",
  semantic_disclaimer:
    "Semantic analysis results, if present, are probabilistic forensic estimations and do not constitute definitive classification.",
  legal_disclaimer:
    "This certificate is generated by automated cryptographic verification software and does not constitute legal advice or admissibility opinion. Consult qualified forensic and legal experts for evidentiary assessments.",
};

// ─── Generator ────────────────────────────────────────────────────────────────

export async function generateVerificationCertificate(
  verifyResult: VerifyResult,
  forensicReport?: ForensicReport,
  semanticResult?: SemanticAnalysisResult
): Promise<VerificationCertificate> {
  const bundle = verifyResult.bundle;
  const now = new Date().toISOString();
  const certId = "cert_" + Date.now().toString(36) + Math.random().toString(36).slice(2, 6);

  const hashMatch = verifyResult.recomputed_hash === bundle.media_hash;

  const cert: VerificationCertificate = {
    aletheia_certificate: "v2",
    certificate_id: certId,
    certificate_class: "PROVENANCE_CERTIFICATE",
    issued_at: now,
    issuer: {
      name: "Aletheia Verification Engine",
      version: "2.0.0",
      infrastructure_note:
        "Client-side verification pending production Rust/Axum attestation server integration. In production, this certificate is signed by the Aletheia CA and RFC 3161 timestamped.",
    },
    subject: {
      media_hash: bundle.media_hash,
      device_id: bundle.device_id,
      capture_timestamp: bundle.timestamp,
      algorithm: "Ed25519 / SHA-256",
      gps: bundle.gps,
      bundle_version: bundle.version,
      ai_disclosure: (bundle as { ai_disclosure?: string }).ai_disclosure ?? "undeclared_origin",
    },
    verification: {
      overall_valid: verifyResult.valid,
      trust_level: "PROVENANCE_VERIFIED",
      trust_score: verifyResult.trust_score,
      hash_match: hashMatch,
      signature_valid: verifyResult.valid,
      timestamp_valid: true,
      replay_protected: !!(bundle.nonce && bundle.nonce.length >= 16),
      checks: verifyResult.checks.map((c) => ({ label: c.label, passed: c.ok })),
    },
    scope_notes: SCOPE,
  };

  if (forensicReport) {
    cert.forensic_audit = {
      synthetic_risk_score: 0,
      verdict: forensicReport.verdict,
      confidence: 0,
      primary_indicators: forensicReport.flags,
      check_count: forensicReport.checks.length,
      checks_passed: forensicReport.checks.filter((c) => c.ok).length,
      provenance_audit_score: forensicReport.overallScore,
    };
  }

  if (semanticResult) {
    if (!cert.forensic_audit) {
      cert.forensic_audit = {
        synthetic_risk_score: semanticResult.syntheticRiskScore,
        verdict: semanticResult.verdictLabel,
        confidence: semanticResult.overallConfidence,
        primary_indicators: semanticResult.primaryIndicators,
        check_count: semanticResult.signals.length,
        checks_passed: semanticResult.signals.filter((s) => s.riskLevel === "low").length,
        provenance_audit_score: 0,
      };
    } else {
      cert.forensic_audit.synthetic_risk_score = semanticResult.syntheticRiskScore;
      cert.forensic_audit.verdict = semanticResult.verdictLabel;
      cert.forensic_audit.confidence = semanticResult.overallConfidence;
    }
  }

  // Self-referential hash (integrity check on the certificate itself)
  const certJson = JSON.stringify(cert);
  cert.certificate_hash = await sha256Hex(new TextEncoder().encode(certJson));

  return cert;
}

// ─── Export Formats ───────────────────────────────────────────────────────────

/** Download certificate as formatted JSON */
export function downloadCertificateJSON(cert: VerificationCertificate): void {
  const blob = new Blob([JSON.stringify(cert, null, 2)], { type: "application/json" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `aletheia-certificate-${cert.certificate_id}.json`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Generate human-readable text certificate */
export function formatCertificateText(cert: VerificationCertificate): string {
  const divider = "═".repeat(60);
  const lines = [
    divider,
    "  ALETHEIA PROVENANCE CERTIFICATE",
    `  ${cert.issuer.name} · Version ${cert.issuer.version}`,
    divider,
    "",
    `Certificate ID:  ${cert.certificate_id}`,
    `Issued:          ${new Date(cert.issued_at).toLocaleString()}`,
    `Class:           ${cert.certificate_class}`,
    "",
    "─".repeat(60),
    "  SUBJECT",
    "─".repeat(60),
    `Media Hash:      ${cert.subject.media_hash}`,
    `Device ID:       ${cert.subject.device_id}`,
    `Captured:        ${new Date(cert.subject.capture_timestamp).toLocaleString()}`,
    `Algorithm:       ${cert.subject.algorithm}`,
    `AI Disclosure:   ${cert.subject.ai_disclosure}`,
    `Bundle Version:  ${cert.subject.bundle_version}`,
    cert.subject.gps
      ? `GPS:             ${cert.subject.gps.lat}, ${cert.subject.gps.lon}`
      : "GPS:             Not included",
    "",
    "─".repeat(60),
    "  VERIFICATION RESULT",
    "─".repeat(60),
    `Overall Valid:   ${cert.verification.overall_valid ? "YES" : "NO"}`,
    `Trust Level:     ${cert.verification.trust_level}`,
    `Trust Score:     ${cert.verification.trust_score}/100`,
    `Hash Match:      ${cert.verification.hash_match ? "PASS" : "FAIL"}`,
    `Signature Valid: ${cert.verification.signature_valid ? "PASS" : "FAIL"}`,
    `Replay Guard:    ${cert.verification.replay_protected ? "PASS" : "FAIL"}`,
    "",
    "  VERIFICATION CHECKS:",
    ...cert.verification.checks.map(
      (c) => `  ${c.passed ? "✓" : "✗"} ${c.label}`
    ),
  ];

  if (cert.forensic_audit) {
    lines.push(
      "",
      "─".repeat(60),
      "  FORENSIC AUDIT",
      "─".repeat(60),
      `Provenance Score: ${cert.forensic_audit.provenance_audit_score}/100`,
      `Forensic Verdict: ${cert.forensic_audit.verdict}`,
      cert.forensic_audit.synthetic_risk_score > 0
        ? `Synthetic Risk:   ${cert.forensic_audit.synthetic_risk_score}%`
        : "",
    );
  }

  lines.push(
    "",
    "─".repeat(60),
    "  SCOPE DISCLAIMER",
    "─".repeat(60),
    "",
    cert.scope_notes.provenance_disclaimer,
    "",
    cert.scope_notes.legal_disclaimer,
    "",
    `Certificate Hash: ${cert.certificate_hash ?? "pending"}`,
    divider,
  );

  return lines.filter((l) => l !== undefined).join("\n");
}

/** Download certificate as plain text */
export function downloadCertificateText(cert: VerificationCertificate): void {
  const blob = new Blob([formatCertificateText(cert)], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `aletheia-certificate-${cert.certificate_id}.txt`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
